// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateUserInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
}

type Mutation struct {
}

type Query struct {
}
